// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcdYkQd1gYnEvI3c5or0BEDLQndxNzetk',
    appId: '1:725556233760:web:87bfc12201af47ae375e45',
    messagingSenderId: '725556233760',
    projectId: 'vapa-app-7f59b',
    authDomain: 'vapa-app-7f59b.firebaseapp.com',
    storageBucket: 'vapa-app-7f59b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vICSd8Y3EXw9PQYTL5JgohXDYhBcXEY',
    appId: '1:725556233760:android:59f84766e2a3abb2375e45',
    messagingSenderId: '725556233760',
    projectId: 'vapa-app-7f59b',
    storageBucket: 'vapa-app-7f59b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8LZtCA_y0jl3IblvTvGcflCiDB_XKpqI',
    appId: '1:725556233760:ios:ff7e7ce47a167489375e45',
    messagingSenderId: '725556233760',
    projectId: 'vapa-app-7f59b',
    storageBucket: 'vapa-app-7f59b.firebasestorage.app',
    iosBundleId: 'com.example.vapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8LZtCA_y0jl3IblvTvGcflCiDB_XKpqI',
    appId: '1:725556233760:ios:ff7e7ce47a167489375e45',
    messagingSenderId: '725556233760',
    projectId: 'vapa-app-7f59b',
    storageBucket: 'vapa-app-7f59b.firebasestorage.app',
    iosBundleId: 'com.example.vapa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcdYkQd1gYnEvI3c5or0BEDLQndxNzetk',
    appId: '1:725556233760:web:2b20e26c8a05e5e1375e45',
    messagingSenderId: '725556233760',
    projectId: 'vapa-app-7f59b',
    authDomain: 'vapa-app-7f59b.firebaseapp.com',
    storageBucket: 'vapa-app-7f59b.firebasestorage.app',
  );

}